### ISSUE TITLE
能不能去掉默认的@符号

### ISSUE THREAD

**Issue by allinu** [ahonn/vim-fileheader#6]
你好，我是普通的vim使用者，很喜欢您的这个项目，现在也在使用
我现在有一个需求，需要对Markdown文件进行全部的自定义

我使用Python将Markdown生成Html文件，里面可以通过设置
```yaml
---
key: value
key: value
key: value
key: value
key: value
---
```
的这种方式提供文档信息，其实现在可以通过已经关闭的那个 issue 解决，可以进行添加，但是每次都需要删除原来的自动生成的信息
而且那个不支持空格的key，所以，可以更改这个插件，去除空格，使用下划线，并去掉@符号么？

麻烦您了

**Comment by ahonn** [comment]
> 而且那个不支持空格的key，所以，可以更改这个插件，去除空格，使用下划线，并去掉@符号么？

这个我没太明白意思？能否给个示例。
另外 markdown 是想要通过配置插件以支持添加 Front Matter 是吧？

**Comment by allinu** [comment]
> 另外 markdown 是想要通过配置插件以支持添加 Front Matter 是吧？

对，不好意思，我表达能力太差了


现在是
```ymal
---
@Author: Liona Maskros <lionacc@163.com>
@Date: 2021-01-26 21:40:03
@Last Modified by: Liona Maskros <lionacc@163.com>
@Last Modified time: 2021-01-26 21:40:10
title:
tags:
description:
categories:
publish: true
secret_code:
isShowComments: false
---
```

我希望的结果是
```yaml
---
Author: Liona Maskros <lionacc@163.com>
Date: 2021-01-25 22:57:44
title: 伪元素与伪类
tags: 前端
CSS
description: 伪元素和伪类可以作为选择器使用，从而避免了创建冗余的无用元素
categories: 前端
技术
publish: true
secret_code:
isShowComments: true
---
```

Front Matter 部分前面的KEY不能有特殊符号，也不能包含空格
